const fs = require('fs');
const path = require('path');

const inputFile = process.argv[2];
if (!inputFile) {
    console.error("Usage: node migrate.js <input_json>");
    process.exit(1);
}

const raw = fs.readFileSync(inputFile, 'utf8');
const domainList = JSON.parse(raw);

// Load existing haproxy.cfg
const cfgPath = '/data/haproxy/haproxy.cfg';
let cfg = fs.readFileSync(cfgPath, 'utf8');

// Identify insertion points
const frontendHttpMarker = "# Dynamic host-based routing (generated by API)";
const backendMarker = "# Dynamic backends (generated by API)";

// Group by target IP to avoid duplicate backends
const backends = {};
domainList.forEach(item => {
    if (!backends[item.target]) {
        backends[item.target] = [];
    }
    backends[item.target].push(item.domain);
});

let aclLinesHttp = [];
let backendLinesHttp = [];
let aclLinesHttps = [];
let backendLinesHttps = [];
let backendDefs = [];

let counter = 100; // Start ID from 100 to avoid conflicts

Object.keys(backends).forEach(targetIp => {
    const domains = backends[targetIp];
    const backendName = `backend_web_${targetIp.replace(/\./g, '_')}`;

    // Define backend once
    backendDefs.push(`backend ${backendName}`);
    backendDefs.push(`    server web_${counter} ${targetIp}:80 check inter 3s fall 3 rise 2`);
    backendDefs.push("");

    domains.forEach(domain => {
        const aclName = `host_${domain.replace(/\./g, '_')}`;

        // HTTP Frontend
        aclLinesHttp.push(`    acl ${aclName} hdr(host) -i ${domain}`);
        // Redirect HTTP to HTTPS
        backendLinesHttp.push(`    http-request redirect scheme https code 301 if ${aclName}`);

        // HTTPS Frontend
        aclLinesHttps.push(`    acl ${aclName} hdr(host) -i ${domain}`);
        backendLinesHttps.push(`    use_backend ${backendName} if ${aclName}`);
    });

    counter++;
});

// Split config by frontends
const parts = cfg.split("frontend https_frontend");
let httpPart = parts[0];
let restPart = "frontend https_frontend" + parts[1];

const backendSplit = restPart.split("# Dynamic backends (generated by API)");
let httpsPart = backendSplit[0];
let footerPart = "# Dynamic backends (generated by API)" + backendSplit[1];

// Inject HTTP rules
const httpInsertIndex = httpPart.lastIndexOf(frontendHttpMarker);
if (httpInsertIndex !== -1) {
    const insertPos = httpInsertIndex + frontendHttpMarker.length;
    const newContent = "\n" + aclLinesHttp.join("\n") + "\n\n" + backendLinesHttp.join("\n") + "\n";
    httpPart = httpPart.slice(0, insertPos) + newContent + httpPart.slice(insertPos);
}

// Inject HTTPS rules
const httpsInsertIndex = httpsPart.lastIndexOf(frontendHttpMarker);
if (httpsInsertIndex !== -1) {
    const insertPos = httpsInsertIndex + frontendHttpMarker.length;
    const newContent = "\n" + aclLinesHttps.join("\n") + "\n\n" + backendLinesHttps.join("\n") + "\n";
    httpsPart = httpsPart.slice(0, insertPos) + newContent + httpsPart.slice(insertPos);
}

// Inject Backends
const backendInsertIndex = footerPart.indexOf(backendMarker);
if (backendInsertIndex !== -1) {
    const insertPos = backendInsertIndex + backendMarker.length;
    const newContent = "\n" + backendDefs.join("\n") + "\n";
    footerPart = footerPart.slice(0, insertPos) + newContent + footerPart.slice(insertPos);
}

// Reassemble
const newCfg = httpPart + httpsPart + footerPart;

fs.writeFileSync(cfgPath, newCfg);
console.log("HAProxy config updated successfully with " + domainList.length + " domains.");
