
import os
import time
import subprocess
import glob
import re

PORTS_FILE_DIR = "/app/config/haproxy/ports" 

def log(msg):
    print(f"[PORT_MANAGER] {msg}", flush=True)

def get_open_ports():
    try:
        # Get list of open ports using iptables
        # Look for ACCEPT rules in INPUT chain
        result = subprocess.run(['iptables', '-L', 'INPUT', '-n', '--line-numbers'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if result.returncode != 0:
            log(f"Error listing iptables rules: {result.stderr}")
            return set()
        
        ports = set()
        # Regex to find dpt:PORT or dports:PORT
        for line in result.stdout.splitlines():
            if "ACCEPT" in line and "tcp" in line:
                match = re.search(r'dpt:(\d+)', line)
                if match:
                    ports.add(f"{match.group(1)}/tcp")
                
                # Check for multiport ranges (e.g. 30000:30100)
                match_range = re.search(r'dpts:(\d+:\d+)', line)
                if match_range:
                    # iptables output uses colon for range, our format uses dash
                    raw_range = match_range.group(1)
                    ports.add(f"{raw_range.replace(':', '-')}/tcp")
                    
        return ports
    except Exception as e:
        log(f"Exception listing ports: {e}")
        return set()

def open_port(port_protocol):
    try:
        log(f"Opening port: {port_protocol}")
        
        proto = "tcp"
        if "/udp" in port_protocol:
            proto = "udp"
            
        port_range = port_protocol.replace("/tcp", "").replace("/udp", "").replace("-", ":")
        
        # Check if port is single or range
        if ":" in port_range: # Range 30000:30100
             # Use multiport module for ranges if available, or just standard dport 
             # Standard -p tcp --dport start:end works
             subprocess.run(['iptables', '-I', 'INPUT', '-p', proto, '--dport', port_range, '-j', 'ACCEPT'], check=True)
        else:
             subprocess.run(['iptables', '-I', 'INPUT', '-p', proto, '--dport', port_range, '-j', 'ACCEPT'], check=True)
             
        return True
    except Exception as e:
        log(f"Failed to open port {port_protocol}: {e}")
        return False

def close_port(port_protocol):
    # Not implementing close logic to avoid accidental lockouts
    return True

def reload_firewall():
    # iptables applies immediately, no reload needed
    pass

def run_port_manager():
    log("Starting Port Manager (IPTables Mode)...")
    if not os.path.exists(PORTS_FILE_DIR):
        try:
            os.makedirs(PORTS_FILE_DIR)
        except:
            pass

    while True:
        try:
            # 1. Read desired ports from file(s) generated by API
            desired_ports = set()
            
            # Helper: Always keep these open
            desired_ports.add("80/tcp")
            desired_ports.add("443/tcp")
            desired_ports.add("8404/tcp")
            desired_ports.add("30000-30100/tcp") 
            desired_ports.add("21/tcp")
            
            # Read from file created by API
            port_files = glob.glob(os.path.join(PORTS_FILE_DIR, "*.txt"))
            for p_file in port_files:
                with open(p_file, 'r') as f:
                    for line in f:
                        line = line.strip()
                        if line:
                            desired_ports.add(line)

            # 2. Get currently open ports
            current_ports = get_open_ports()

            # 3. Open missing ports
            for port in desired_ports:
                if port not in current_ports:
                    open_port(port)

        except Exception as e:
            log(f"Error in cycle: {e}")
        
        time.sleep(10)

if __name__ == "__main__":
    pass
